/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/keyboard.glb --transform --types 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Circle: THREE.Mesh;
    Cube: THREE.Mesh;
    Plane: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
  };
};

export function KeyboardModel(props: React.ComponentPropsWithoutRef<"group">) {
  const { nodes, materials } = useGLTF(
    "/keyboard-transformed.glb",
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.PaletteMaterial002}
        onPointerOver={(e) => {
          e.stopPropagation();
          document.body.style.cursor = "pointer";
        }}
        onPointerOut={() => {
          document.body.style.cursor = "auto";
        }}
        onClick={(e) => {
          e.stopPropagation();
          console.log("You clicked the Cube mesh!");
        }}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials.PaletteMaterial003}
      />
    </group>
  );
}

useGLTF.preload("/keyboard-transformed.glb");
